server/website/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, HiddenField, FileField
from wtforms.validators import DataRequired

class AssistantForm (FlaskForm):
    message = StringField('Mensaje', id='mensaje', validators=[DataRequired()])
    submit = SubmitField('Enviar', render_kw={'id': 'submit-button'})
    
    
class CounterAssistantForm (FlaskForm):
    message = StringField('Mensaje', id='mensaje', validators=[DataRequired()], render_kw={'placeholder':'Escribe tu mensaje'})
    
class AssistantHandlerForm(FlaskForm):
    id = HiddenField('ID', id='id', render_kw={'readonly': True})
    id_openai = HiddenField('ID OpenAI', id='id_openai', render_kw={'readonly': True})
    name = StringField('Nombre del asistente', id='name', validators=[DataRequired()])
    model_id = SelectField('Modelo', id='model_id', coerce=str, validators=[DataRequired()])
    version_id = SelectField('Versión', id='version_id', coerce=str, validators=[DataRequired()])
    description = StringField('Descripción', id='description', validators=[DataRequired()])
    instructions = StringField('Instrucciones', id='instructions', validators=[DataRequired()])
    apikey = StringField('API Key', id='apikey', render_kw={'readonly': True})
    avatar = FileField('Avatar', id='avatar')
    submit = SubmitField('Guardar', render_kw={'id': 'submit-button'})

class AssistantFileForm(FlaskForm):
    file = FileField('Selecciona el archivo', id='customFile', validators=[DataRequired()])
    save = SubmitField('Enviar', render_kw={'id': 'submit-button'})
    cancel = SubmitField('Cancelar', render_kw={'id': 'cancel-button'})

class ModelsForm(FlaskForm):
    id = StringField('ID', id='id', render_kw={'readonly': True})
    name = StringField('Nombre del modelo', id='name', validators=[DataRequired()])
    active = StringField('Activo', id='active', validators=[DataRequired()])
    

server/website/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2024 - present 
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

server/website/home/routes.py
import os
from flask import render_template, current_app, flash, request, jsonify, url_for, session, redirect, send_file
from flask_login import login_required, current_user
from website.home import blueprint
from website.home.forms import AssistantForm, CounterAssistantForm, AssistantHandlerForm, ModelsForm, AssistantFileForm
from website.home.models import AssistantsModels, Assistants, AssistantsVersion, AssistantsApiKey, AssistantsFiles, AssistantsVector
import time 
from datetime import datetime
from website.home.models import Assistants
#from website.home.controller.assistant import AssistantController
from website.home.controller.assistant_v2 import AssistantController
from website.auth.api_key import require_api_key
from website import csrf, db
import secrets
import json
import traceback
from website.log import logging_decorator



@blueprint.route('/', methods=['GET'])
def index():
    return render_template('home/index.html')

@blueprint.route('/asistentes', methods=['GET'])
@login_required
def assistants():
    assistants = Assistants.query.filter_by(user_id=current_user.id).all()
    for assistant in assistants:
        print(f'{assistant}')
    return render_template('home/assistants.html', segment='assistants-list', assistants=assistants)

@blueprint.route('/asistentes/form', methods=['GET', 'POST'])
@blueprint.route('/asistentes/form/<assistant_id>', methods=['GET', 'POST'])
@login_required
def handler_assistant_form(assistant_id=None):   
    models = AssistantsModels.query.all()
    model_choices = [(model.id, model.name) for model in models]
    version = AssistantsVersion.query.all()
    version_choices = [(version.id, version.name) for version in version]

    if assistant_id:
        assistant = Assistants.query.filter_by(id=assistant_id).first()
        form = AssistantHandlerForm(obj=assistant)
        form.model_id.choices = model_choices
        form.version_id.choices = version_choices
        if assistant.apikey:
            form.apikey.data = assistant.apikey.apikey
        if form.validate_on_submit() and request.method == 'POST' and form.submit.data:
            current_app.logger.info(f'entro a actualizar asistente')   
            try:
                assistant.name = form.name.data
                assistant.model_id = form.model_id.data
                assistant.version_id = form.version_id.data
                assistant.instructions = form.instructions.data
                assistant.description = form.description.data
                current_app.logger.info(f'assistant: {assistant}')
                db.session.commit()
                flash("Asistente actualizado correctamente.", 'success')
                return redirect(url_for('home_blueprint.assistants'))
            except Exception as e:
                db.session.rollback()
                error_message = f"Error al actualizar el asistente: {str(e)}"
                flash(error_message, 'danger')
                error_traceback = traceback.format_exc()
                current_app.logger.error(f"{error_message}\n{error_traceback}")
        return render_template('home/assistant_form.html', segment='assistants-list', form=form, assistant=assistant)
    else:
        form = AssistantHandlerForm()
        form.model_id.choices = model_choices
        form.version_id.choices = version_choices
        if form.validate_on_submit() and request.method == 'POST':
            try:
                modelo = AssistantsModels.query.filter_by(id=form.model_id.data).first()
                data = {
                    'name': form.name.data,
                    'model_id': modelo.oa_name,
                    'version_id': form.version_id.data,
                    'instructions': form.instructions.data,
                    'description': form.description.data
                }
                current_app.logger.info(f'data: {data}')
                assistant_id = AssistantController().create_assistant(data)
                current_app.logger.info(f'assistant_id: {assistant_id}')
                assistant = Assistants(
                    id_openai = assistant_id,
                    name = form.name.data,
                    user_id = current_user.id,
                    model_id = form.model_id.data,
                    version_id = form.version_id.data,
                    instructions = form.instructions.data,
                    description = form.description.data
                )
                current_app.logger.info(f'assistant: {assistant}')
                db.session.add(assistant)
                db.session.commit()
                flash("Asistente creado correctamente.", 'success')
                return redirect(url_for('home_blueprint.assistants'))
            except Exception as e:
                db.session.rollback()
                error_message = f"Error al crear el asistente: {str(e)}"
                flash(error_message, 'danger')
                error_traceback = traceback.format_exc()
                current_app.logger.error(f"{error_message}\n{error_traceback}")
        return render_template('home/assistant_form.html', segment='assistants-list', form=form)

@blueprint.route('/assistant_addFile', methods=['POST'])
@login_required
def assistant_addFile():
    try:
        assistant_id = request.form.get('assistant_id')
        file = request.files.get('file')
        if not assistant_id or not file:
            return jsonify({'status': 'error', 'message': 'No se han recibido los datos necesarios'}), 400
        
        assistant = Assistants.query.get(assistant_id)
        if not assistant:
            return jsonify({'status': 'error', 'message': 'No se ha encontrado el asistente'}), 404
        
        # validar si el asistente ya tiene un vector, en caso contrario crearlo
        vector_obj = AssistantsVector.query.filter_by(assistant_id=assistant_id).first()
        if not vector_obj:
            vector_obj = AssistantsVector(assistant_id=assistant_id)
            db.session.add(vector_obj)
            db.session.commit()

        path = f'home/controller/files/{current_user.id}/{assistant_id}'
        absolute_path = os.path.join('website', path)
        if not os.path.exists(absolute_path):
            os.makedirs(absolute_path)
        file_path = os.path.join(absolute_path, file.filename)
        file.save(file_path)
        assistantsFile = AssistantsFiles(name=file.filename, path=path, assistant_id=assistant_id, vector_id=vector_obj.id ,type=os.path.splitext(file.filename)[1], size= os.path.getsize(file_path))
        current_app.logger.info(f'assistantFile: {assistantsFile}') 
    except Exception as e:
        current_app.logger.error(traceback.format_exc())
    try:
        db.session.add(assistantsFile)
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        current_app.logger.error(traceback.format_exc())
        error_traceback = traceback.format_exc()
        current_app.logger.error(f"Error al guardar el archivo: {str(e)}\n{error_traceback}")
        return jsonify({'status': 'error', 'message': str(error_traceback)}), 400
    
    # Devuelve los datos del archivo recién subido
    return jsonify({
        'status': 'success',
        'message': f'Archivo {file.filename} cargado correctamente.',
        'file': {
            'id': assistantsFile.id,
            'name': assistantsFile.name,
            'type': assistantsFile.type,
            'size': assistantsFile.size,
            'upload': assistantsFile.upload,
            'vector': assistantsFile.vector_id,
            'created_at': assistantsFile.created_at.strftime('%Y-%m-%d %H:%M:%S')
        }
    }), 200

@blueprint.route('/assistant_run', methods=['POST'])
@login_required
def assistant_run():
    assistant_id = request.form.get('assistant_id')
    if not assistant_id:
        return jsonify({'status': 'error', 'message': 'No se ha especificado el asistente'}), 400
    assistant = Assistants.query.get(assistant_id)
    if not assistant:
        return jsonify({'status': 'error', 'message': 'No se ha encontrado el asistente'}), 404
    # Obtener los archivos no subidos desde la base de datos
    files = AssistantsFiles.query.filter_by(assistant_id=assistant_id, upload=False).all()
    current_app.logger.info(f'files to upload: {files}')
    if not files:
        return jsonify({'status': 'error', 'message': 'No se han encontrado archivos para subir'}), 404
    # Construir la lista de rutas con los nuevos nombres de archivo
    file_paths = [os.path.join('website', file.path, file.name) for file in files]
    name = f'{assistant.name}-Datos'
    data = {
        'name': name,
        'files': files,
        'assistant_id': assistant.id_openai
    }
    try:
        vector = AssistantsVector.query.filter_by(assistant_id=assistant_id).first()
        assistant_openai, vector_store_id, file_batch = AssistantController().run_assistant(data, assistant.id, vector)
        current_app.logger.info(f'vector_store_id: {vector_store_id}')
        current_app.logger.info(f'file_batch: {file_batch}')
        vector.vector = vector_store_id
        db.session.commit()
        assistant.vector_id = vector.id
        # Actualizar estado de los archivos
        updated_files = []
        for file in files:
            file_obj = AssistantsFiles.query.get(file.id)
            file_obj.upload = True
            updated_files.append({
                'id': file_obj.id,
                'upload': file_obj.upload
            })
        db.session.commit()
        # Actualizar archivos para obtenr el id de openai
        files_batch = AssistantController().readFiles(assistant.id)
        
        flash("Asistente ejecutado correctamente.", 'success')
        # Prepara los datos para la respuesta
        current_app.logger.info(f'updated_files: {updated_files}')
        return jsonify({'status': 'success', 'updated_files': updated_files}), 202
    except Exception as e:

server/website/templates/home/api_key.html
{% extends "layouts/base_content.html" %}

{% block title %} Api-Key {% endblock %} 


{% block header %}
<div class="flex justify-between grow">
    <h1 class="text-xl text-slate-200">Api-Key</h1>

    <div class="bg-emerald-800 hover:bg-emerald-700 rounded-lg transition-all ease-in-out duration-300 px-2 py-1 flex justify-between">
        <a href="{{ url_for('home_blueprint.assistants') }}" class="flex items-center" > 
            <div class="grow flex flex-row items-center">
                <svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 20"  fill="none"  stroke="currentColor"  stroke-width="2"  
                stroke-linecap="round"  stroke-linejoin="round"  class="stroke-slate-200"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                <span class="text-slate-200">Crear</span>
            </div>
        </a>
    </div>
</div> 
{% endblock %} 

{% block content %} 
<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis similique non unde ipsa. Necessitatibus saepe nemo ipsum odit praesentium adipisci similique dolore. Similique reiciendis sit neque perspiciatis, necessitatibus incidunt nostrum!</p>
{% endblock %}

server/website/templates/home/assistants.html
{% extends "layouts/base_content.html" %}

{% block head %} <meta name="csrf-token" content="{{ csrf_token() }}"> {% endblock %}

{% block title %} Asistentes {% endblock %} 


{% block header %}
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Asistentes</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Home</a></li>
            <li class="breadcrumb-item active">Asitentes</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
 
{% endblock %} 

{% block content %} 
<!-- Content Wrapper. Contains page content -->

    

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-solid">
        <div class="card-header">
          <h3 class="card-title">Listado de Asistentes</h3>
          <div style="float: right;">
            <button class="btn btn-primary"
              type="button" onclick="window.location.href='{{ url_for( 'home_blueprint.handler_assistant_form' )}}';">
              <i class="fas fa-plus"></i>
              Agregar Asistente
            </button>
          </div>
        </div>
        <div class="card-body pb-0">
          <div class="row">
            {% for assistant in assistants %}
            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
              <div class="card bg-light d-flex flex-fill">
                <div class="card-header border-bottom-0 text-lg">
                 <b>Asistente virtual inteligente</b>
                </div>
                <div class="card-body pt-0">
                  <div class="row">
                    <div class="col-7">
                      <h2 class="lead"><b>{{ assistant.name }}</b></h2>
                      <h2 class="lead" id="assistant-id-{{ assistant.id }}" style="display: none;">{{ assistant.id }}</h2>
                      <p class="text-muted text-sm" style="max-height: 50px; overflow:clip;"><b>Instrucciones: </b> {{assistant.instructions}} </p>
                      <ul class="ml-4 mb-0 fa-ul text-muted">
                        <li class="small"><span class="fa-li"><i class="fas fa-lg fa-code-branch"></i></span> {{ assistant.model.name }}</li>
                        <li class="small"><span class="fa-li"><i class="fab fa-lg fa-connectdevelop"></i></span> {{ assistant.version.name }}</li>
                      </ul>
                    </div>
                    <div class="col-5 text-center">
                      <img src="{{url_for('static', filename='images/greetbotix.png')}}" alt="user-avatar" class="img-circle img-fluid" style="aspect-ratio: 1; width: 50%;">
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <div class="text-right">
                    {% if assistant.apikey %}
                    <a id="ApiKeyAssistantCopy-{{ assistant.id }}" class="btn btn-sm bg-teal" title="Copiar Api-Key">
                      <i class="fas fa-user-lock"></i>
                    </a>
                    {% endif %}
                    <a href="{{url_for('home_blueprint.handler_assistant_form', assistant_id=assistant.id)}}" class="btn btn-sm btn-primary" title="Detalles del asistente">
                      <i class="fas fa-robot"></i> Detalles del asistente
                    </a>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            
          </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          <nav aria-label="Contacts Page Navigation">
            <ul class="pagination justify-content-center m-0">
              <!-- <li class="page-item active"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">4</a></li>
              <li class="page-item"><a class="page-link" href="#">5</a></li>
              <li class="page-item"><a class="page-link" href="#">6</a></li>
              <li class="page-item"><a class="page-link" href="#">7</a></li>
              <li class="page-item"><a class="page-link" href="#">8</a></li> -->
            </ul>
          </nav>
        </div>
        <!-- /.card-footer -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script  src="{{url_for('static', filename='js/home/assistant.js')}}"></script>
{% endblock %}

server/website/templates/home/chatbot.html
{% extends "layouts/base_content.html" %}

{% block title %} GreetBotIX {% endblock %} 

{% block header %}
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>GreetBot</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Home</a></li>
            <li class="breadcrumb-item active">GreetBot</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
{% endblock %} 

{% block content %}
    <!-- teal blue olive navy lightblue info secondary primary -->
    <div class="card card-primary direct-chat direct-chat-lightblue .card-outline" style="margin: 0 15rem; min-height: 600px;">
        <div class="card-header">
            <h3 class="card-title">Asistente</h3>
        </div>
    <!-- /.card-header -->
        <div class="card-body">
            <!-- Conversations are loaded here -->
            <div class="direct-chat-messages" id="direct-chat-messages" style="min-height: 550px;">
            
        </div>
        <!--/.direct-chat-messages-->
                
    <!-- /.direct-chat-pane -->
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        <form id="formMensaje" method="POST" autocomplete="off" 
          data-assistant-id="{{assistant.id}}" data-asistant="{{ assistant.name | safe }}"
          data-user-id="{{current_user.id}}" data-username="{{ current_user.username | safe }}" 
          data-user-image="{{current_user.image_path}}" data-user-type="user">
            {{ form.hidden_tag() }}
            {{ form.csrf_token() }}
            <div class="input-group">
              <div id="typingIndicator" style="display: none;">Escribiendo...</div>
                {{ form.message(class="form-control", placeholder="Escribe tu mensaje ...") }}
                <span class="input-group-append">
                    {{ form.submit(class="btn btn-primary") }}
                </span>
            </div>
        </form>
    </div>
    
    
    <!-- /.card-footer-->
</div>

{% endblock %} 

{% block javascripts %} 
<script src="{{url_for('static', filename='js/chatbot.js')}}"></script>
{% endblock %}

server/website/templates/home/credit.html
{% extends "layouts/base_content.html" %}

{% block title %} GreetBotIX | Credito {% endblock %} 

{% block header %}
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>GreetBot | Credito</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Home</a></li>
            <li class="breadcrumb-item active">Credito</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
{% endblock %} 

{% block content %}
    <!-- teal blue olive navy lightblue info secondary primary -->
    <div class="card card-primary direct-chat direct-chat-lightblue .card-outline" style="margin: 0 15rem; min-height: 600px;">
        <div class="card-header">
            <h3 class="card-title">Chat credito</h3>
        </div>
    <!-- /.card-header -->
        <div class="card-body">
            <!-- Conversations are loaded here -->
            <div class="direct-chat-messages" id="direct-chat-messages">
            
        </div>
        <!--/.direct-chat-messages-->
                
    <!-- /.direct-chat-pane -->
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        <form id="formMensaje" method="POST" autocomplete="off" 
          data-user-id="{{current_user.id}}" data-username="{{ current_user.username | safe }}" 
          data-user-image="{{current_user.image_path}}" data-user-type="user">
            {{ form.hidden_tag() }}
            {{ form.csrf_token() }}
            <div class="input-group">
              <div id="typingIndicator" style="display: none;">Escribiendo...</div>
                {{ form.message(class="form-control", placeholder="Escribe tu mensaje ...") }}
                <span class="input-group-append">
                    {{ form.submit(class="btn btn-primary") }}
                </span>
            </div>
        </form>
    </div>
    
    
    <!-- /.card-footer-->
</div>

{% endblock %} 

{% block javascripts %} 
<script src="{{url_for('static', filename='js/chatbot.js')}}"></script>
{% endblock %}

server/website/templates/home/finance.html
{% extends "layouts/base_content.html" %}

{% block title %} GreetBotIX | Finanzas {% endblock %} 

{% block header %}
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>GreetBot | Finanzas</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Home</a></li>
            <li class="breadcrumb-item active">Finanzas</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
{% endblock %} 

{% block content %}
    <!-- teal blue olive navy lightblue info secondary primary -->
    <div class="card card-primary direct-chat direct-chat-lightblue .card-outline" style="margin: 0 15rem; min-height: 600px;">
        <div class="card-header">
            <h3 class="card-title">Chat financiero</h3>
        </div>
    <!-- /.card-header -->
        <div class="card-body">
            <!-- Conversations are loaded here -->
            <div class="direct-chat-messages" id="direct-chat-messages">
            
        </div>
        <!--/.direct-chat-messages-->
                
    <!-- /.direct-chat-pane -->
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        <form id="formMensaje" method="POST" autocomplete="off" 
          data-user-id="{{current_user.id}}" data-username="{{ current_user.username | safe }}" 
          data-user-image="{{current_user.image_path}}" data-user-type="user">
            {{ form.hidden_tag() }}
            {{ form.csrf_token() }}
            <div class="input-group">
              <div id="typingIndicator" style="display: none;">Escribiendo...</div>
                {{ form.message(class="form-control", placeholder="Escribe tu mensaje ...") }}
                <span class="input-group-append">
                    {{ form.submit(class="btn btn-primary") }}
                </span>
            </div>
        </form>
    </div>
    
    
    <!-- /.card-footer-->
</div>

{% endblock %} 

{% block javascripts %} 
<script src="{{url_for('static', filename='js/chatbot.js')}}"></script>
{% endblock %}