server/website/settings/models.py
from website import db
from website.home.utils.keyUtils import GenerateUUIDStyled

server/website/settings/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2024 - present 
"""

from flask import Blueprint

blueprint = Blueprint(
    'settings_blueprint',
    __name__,
    url_prefix=''
)

server/website/settings/routes.py
from website.settings import blueprint
from flask import render_template, flash, current_app
from flask_login import login_required, current_user
from website.home.models import AssistantsModels, AssistantsVersion
from website.auth.models import User



########################
# Apartado de usuarios #
########################
@blueprint.route('/configuracion_usuario', methods=['GET'])
def user_settings():
    user = User.query.get(current_user.id)
    if not user:
        return flash('No se ha encontrado el usuario', 'danger')
    current_app.logger.info(f'User settings for user_id: {user}')
    return render_template('settings/user_settings.html')




@blueprint.route('/listar_modelos', methods=['GET'])
@login_required
def list_models():
    models = AssistantsModels.query.all()
    return render_template('settings/models_list.html', segment='assistants-models', models=models)

@blueprint.route('/listar_versiones', methods=['GET'])
@login_required
def list_versions():
    versions = AssistantsVersion.query.all()
    return render_template('settings/versions_list.html', segment='assistants-version', versions=versions)

@blueprint.route('/modelos/form', methods=['GET', 'POST'])
@blueprint.route('/modelos/form/<model_id>', methods=['GET', 'POST'])
@login_required
def handle_model_form(model_id=None):
    current_app.logger.info(f'Handling model form for model_id: {model_id}')
    return render_template('settings/models_form.html', segment='assistants-models')


@blueprint.route('/versiones/form', methods=['GET', 'POST'])
@blueprint.route('/versiones/form/<version_id>', methods=['GET', 'POST'])
@login_required
def handle_version_form(version_id=None):
    current_app.logger.info(f'Handling version form for version_id: {version_id}')
    return render_template('settings/versions_form.html', segment='assistants-version')

server/website/templates/settings/models_list.html
{% extends "layouts/base_content.html" %}

{% block title %} Modelos {% endblock %} 

{% block stylesheets %} 
  <!-- DataTables -->
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/dist/css/adminlte.min.css')}}">

{% endblock %}

{% block header %}
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Modelos</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Listado de modelos</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
{% endblock %} 

{% block content %} 
<!-- Content Wrapper. Contains page content -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                          <h3 class="card-title">Listado de modelos</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <table id="models-data" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Modelo</th>
                                            <th>Activo</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for model in models %}
                                        <tr data-url="{{ url_for('settings_blueprint.handle_model_form', model_id=model.id) }}" style="cursor:pointer;">
                                                <td>{{model.id}}</td>
                                                <td>{{model.name}}</td>
                                                <td>{{model.active}}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                      <th>Id</th>
                                      <th>Modelo</th>
                                      <th>Activo</th>
                                    </tr>
                                    </tfoot>
                                  </table>
                            </div>
                          
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

{% endblock %}
{% block javascripts %} 
<!-- DataTables  & Plugins -->
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/jszip/jszip.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/pdfmake/pdfmake.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/pdfmake/vfs_fonts.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{url_for('static', filename='AdminLTE/dist/js/adminlte.min.js')}}"></script>

<script src="{{url_for('static', filename='js/settings/models_list.js')}}"></script>
{% endblock %}

server/website/templates/settings/settings.html
{% extends "layouts/base_logged.html" %}

{% block title %} Settings {% endblock %} 


{% block content %}
<div class="ml-16 mt-16">
    <p>hola</p>
</div>


{% endblock %}

server/website/templates/settings/user_settings.html
{% extends "layouts/base_content.html" %}

{% block title %} Usuario {% endblock %} 

server/website/templates/settings/versions_list.html
{% extends "layouts/base_content.html" %}

{% block title %} Versiones {% endblock %} 


{% block header %}
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Versiones</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Listado de versiones</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  {% block stylesheets %} 
  <!-- DataTables -->
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{url_for('static', filename='AdminLTE/dist/css/adminlte.min.css')}}">

  {% endblock %}
 
{% endblock %} 

{% block content %} 
<!-- Content Wrapper. Contains page content -->

    

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                          <h3 class="card-title">Listado de versiones</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <table id="models-data" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Versión</th>
                                            <th>Creación</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for version in versions %}
                                        <tr data-url="{{ url_for('settings_blueprint.handle_version_form', version_id=version.id) }}" style="cursor:pointer;">
                                                <td>{{version.id}}</td>
                                                <td>{{version.name}}</td>
                                                <td>{{version.created_at}}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                      <th>Id</th>
                                      <th>Versión</th>
                                      <th>Creación</th>
                                    </tr>
                                    </tfoot>
                                  </table>
                            </div>
                          
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

{% endblock %}
{% block javascripts %} 

<!-- DataTables  & Plugins -->
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/jszip/jszip.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/pdfmake/pdfmake.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/pdfmake/vfs_fonts.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js')}}"></script>
<script src="{{url_for('static', filename='AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{url_for('static', filename='AdminLTE/dist/js/adminlte.min.js')}}"></script>

<script src="{{url_for('static', filename='js/settings/models_list.js')}}"></script>
{% endblock %}